image:
  tag: v0.10.1

config:
  datasource:
    password: postgresql://superfight:superfight@fights:5432/fight,postgresql://superman:superman@heroes:5432/hero,postgresql://superbad:superbad@villains:5432/villain
# Specifies if datasource should be sourced from secret value in format: postgresql://login:password@hostname:port/dbname?sslmode=disable
# Multiple Postgres databases can be configured by comma separated postgres connection strings
#  datasourceSecret:
#    # Secret name
#    name: prometheus-postgres-exporter
#    # Connection string key inside secret
#    key: data_source_password

service:
  port: 9187
  annotations:
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"

serviceMonitor:
  enabled: true

rbac:
  # Specifies whether RBAC resources should be created
  create: false
  # Specifies whether a PodSecurityPolicy should be created
  pspEnabled: false

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: false
