apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
    name: fights
spec:
    teamId: "quarkus-super-heroes"
    volume:
        size: 1Gi
    numberOfInstances: 2
    users:
        superfight:  # database owner
            - superuser
            - createdb
    databases:
        fight: superfight  # dbname: owner
    postgresql:
        version: "16"
