apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
    name: heroes
spec:
    teamId: "quarkus-super-heroes"
    volume:
        size: 10Gi
    numberOfInstances: 2
    users:
        superman:  # database owner
            - superuser
            - createdb
    databases:
        hero: superman  # dbname: owner
    postgresql:
        version: "16"
