---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
      app: "quarkus-workshop-stat"
      version: "01"
      group: "super-heroes"
  name: "quarkus-workshop-stat"
spec:
  replicas: 1
  selector:
      matchLabels:
          app: "quarkus-workshop-stat"
          version: "01"
          group: "super-heroes"
  template:
      metadata:
          labels:
              app: "quarkus-workshop-stat"
              version: "01"
              group: "super-heroes"
      spec:
          containers:
          - image: "esara/quarkus-workshop-statistic"
            imagePullPolicy: "IfNotPresent"
            name: "quarkus-workshop-stat"
            ports:
              - containerPort: 8080
            env:
                - name: "KUBERNETES_NAMESPACE"
                  valueFrom:
                    fieldRef:
                      fieldPath: "metadata.namespace"
                - name: QUARKUS_HTTP_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: stat-config
                      key: port
                - name: KAFKA_BOOTSTRAP_SERVERS
                  valueFrom:
                    configMapKeyRef:
                      name: stat-config
                      key: kafka
#                - name: QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
#                  value: http://grafana-agent.monitoring:4317
---
apiVersion: "v1"
kind: "Service"
metadata:
    labels:
        app: "quarkus-workshop-stat"
        version: "01"
        group: "super-heroes"
    name: "quarkus-workshop-stat"
spec:
    ports:
        - name: "http"
          port: 8080
    selector:
        app: "quarkus-workshop-stat"
        version: "01"
        group: "super-heroes"
    type: "ClusterIP"
