#kind: Gateway
#apiVersion: gateway.networking.k8s.io/v1beta1
#metadata:
#    name: internal-http
#spec:
#    # Specify an existing GatewayClass.
#    gatewayClassName: gke-l7-rilb
#    listeners:
#        # Listen for HTTP traffic on port 80.
#        - name: http
#          protocol: HTTP
#          port: 80
#---
#apiVersion: gateway.networking.k8s.io/v1beta1
#kind: HTTPRoute
#metadata:
#    name: quarkus
#spec:
#    parentRefs:
#    - name: internal-http
#      namespace: quarkus-super-heroes
#    rules:
#    - backendRefs:
#      - name: quarkus-workshop-ui
#        namespace: quarkus-super-heroes
#        port: 8080
#    - backendRefs:
#      - name: quarkus-workshop-fight
#        namespace: quarkus-super-heroes
#        port: 8080
#      matches:
#      - path:
#          type: PathPrefix
#          value: /api/fights
#---
#apiVersion: gateway.networking.k8s.io/v1beta1
#kind: HTTPRoute
#metadata:
#    name: quarkus-stats
#spec:
#    parentRefs:
#        - name: internal-http
#          namespace: quarkus-super-heroes
#    rules:
#        - backendRefs:
#              - name: quarkus-workshop-stat
#                namespace: quarkus-super-heroes
#                port: 8080
