apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    labels:
        k8s-app: quarkus-super-heroes-monitor
    name: quarkus-super-heroes
    namespace: quarkus-super-heroes
spec:
    endpoints:
        - interval: 30s
          targetPort: 8080
          path: /q/metrics
          scheme: http
    selector:
        matchLabels:
            group: super-heroes
