apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: fights
spec:
  forProvider:
    region: us-east-2
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    autogeneratePassword: true
    backupRetentionPeriod: 0
    dbInstanceClass: db.t3.micro # needs to support engine and -version (see AWS Docs: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html#Concepts.DBInstanceClass.Support)
    dbName: fight
    engine: postgres
    engineVersion: "14.7"
    allowMajorVersionUpgrade: true # unset per default (Note: supported dbInstanceClass and dbParameterGroup with correct dbParameterGroupFamily needed, before majorVersion upgrade possible; applyImmediately matters)
    masterUsername: superfight
    masterUserPasswordSecretRef:
      key: password
      name: superfight-fights-secret
      namespace: crossplane-system
    preferredBackupWindow: "7:00-8:00"
    preferredMaintenanceWindow: "Sat:8:00-Sat:11:00"
    publiclyAccessible: true
    skipFinalSnapshot: true
    storageEncrypted: false
    storageType: gp2
    applyImmediately: true
  writeConnectionSecretToRef:
    name: fights-connection-secret
    namespace: quarkus-super-heroes
  providerConfigRef:
    name: default
