apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: heroes
spec:
  forProvider:
    region: us-east-2
    allocatedStorage: 20
    autogeneratePassword: true
    backupRetentionPeriod: 0
    dbInstanceClass: db.t4g.micro # needs to support engine and -version (see AWS Docs: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html#Concepts.DBInstanceClass.Support)
    dbName: hero
    engine: postgres
    engineVersion: "18.1"
    allowMajorVersionUpgrade: true # unset per default (Note: supported dbInstanceClass and dbParameterGroup with correct dbParameterGroupFamily needed, before majorVersion upgrade possible; applyImmediately matters)
    masterUsername: superman
    masterUserPasswordSecretRef:
      key: password
      name: superman-heroes-secret
      namespace: crossplane-system
    preferredBackupWindow: "7:00-8:00"
    preferredMaintenanceWindow: "Sat:8:00-Sat:11:00"
    publiclyAccessible: true
    skipFinalSnapshot: true
    applyImmediately: true
  writeConnectionSecretToRef:
    name: heroes-connection-secret
    namespace: quarkus-super-heroes
