apiVersion: kafka.aws.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: super-heroes
spec:
  forProvider:
    clusterName: super-heroes
    region: us-east-2
    brokerNodeGroupInfo:
      clientSubnets:
      - subnet-081ec67fcb58c84d8
      - subnet-09fa95e81730c8202
      - subnet-0ec3f08a1f28407d8
      securityGroups:
      - sg-0ca2fc2bdfa907816
      instanceType: kafka.m7g.large
      storageInfo:
        ebsStorageInfo:
          volumeSize: 10
      connectivityInfo:
        publicAccess:
          type: SERVICE_PROVIDED_EIPS
    kafkaVersion: 4.1.x.kraft
    clientAuthentication:
      sasl:
        scram:
          enabled: true
    configurationInfo:
      arnRef:
        name: quarkus-configuration
      revision: 1
    numberOfBrokerNodes: 3
  writeConnectionSecretToRef:
    name: kafka-connection-secret
    namespace: quarkus-super-heroes
  providerConfigRef:
    name: default
---
apiVersion: kafka.aws.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: quarkus-configuration
  namespace: crossplane-system
spec:
  forProvider:
    region: us-east-2
    properties:
    - auto.create.topics.enable=true
    - allow.everyone.if.no.acl.found=false
    - num.partitions=1
  providerConfigRef:
    name: default
